### ISSUE TITLE
Back Button/Back Stack Isn't Working Correctly

### ISSUE THREAD

**Issue by primehalo** [drusak/tabactivity#1]
I think I found a fairly significant bug relating to the back button/back navigation stack.

Start the app. In TAB_1 add a fragment to the current tab. Switch to TAB_2 and add a fragment to the current tab. Switch to TAB_1 and hit the back button. The fragment in TAB_2 is popped instead of the fragment in TAB_1. What you see is that the back button in the action bar goes away but TAB_1 still shows "Second Level". If you switch to TAB_2 you see "Tab 2 Root".

**UPDATE**
Looks like it's because fragment tags aren't unique, so `mBaseTabActivity.getSupportFragmentManager().findFragmentByTag(currentFragmentTag)` isn't returning the fragment we were trying to get.

I attempted to fix this by building unique fragment tags. I put this line inside `addFragmentInTab()`:

```
String fragmentId = tabId.getUniqueTabIdName() + ':' + getCountOfFragmentsInTab(tabId) + ':' + fragment.getFragmentId();
```

And then replaced `fragment.getFragmentId()` with `fragmentId`. I created the `getCountOfFragmentsInTab()` function based on your `getCountOfFragmentsInCurrentTab()` function.

So far this seems to be working.

**Comment by drusak** [comment]
Hi! 

Thanks for reporting the issue and finding the solution.
So if it works I'm glad to hear that. Anyway I'll take a look at it ASAP.

Dmitry

**Comment by drusak** [comment]
Hi!

You are right, when you add the same fragment (instance of same Class) to several tabs then you can have a collision. Right now when you add Fragment to Tab it will use method _getFragmentId()_ which returns ClassName by default.
I agree There is should be a fix for such a case. I'll think over the solution, probably your one is the best here.

Note:
If you have all fragments as unique classes, this problem is gone.

Dmitry

**Comment by drusak** [comment]
@primehalo Your solution is quite right. I've improved it a little bit and pushed. Currently tag for the fragment in tab counting as path to it, e.g. if We have such stack Tab1 -> Fragment11 -> Fragment12 then top fragment will be pushed to FragmentManager with tag "Tab1|Fragment11|Fragment12". I think It is more readable than in your case, but the result is the same.

Thanks for raising this issue!
